{% set version = '1.12' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmltable
  version: {{ version|replace("-", "_") }}

source:
  fn: htmlTable_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/htmlTable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htmlTable/htmlTable_{{ version }}.tar.gz
  sha256: 42f50b8d8704460388cc55708fd9159b576261ab8d3f5968cf24d6b3b619a1d8

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-htmltools
    - r-htmlwidgets
    - r-knitr >=1.6
    - r-magrittr >=1.5
    - r-rstudioapi >=0.6
    - r-stringr
  run:
    - r-base
    - r-checkmate
    - r-htmltools
    - r-htmlwidgets
    - r-knitr >=1.6
    - r-magrittr >=1.5
    - r-rstudioapi >=0.6
    - r-stringr

test:
  commands:
    - $R -e "library('htmlTable')"           # [not win]
    - "\"%R%\" -e \"library('htmlTable')\""  # [win]

about:
  home: http://gforge.se/packages/
  license: GPL (>= 3)
  summary: Tables with state-of-the-art layout elements such as row spanners, column spanners,
    table spanners, zebra striping, and more. While allowing advanced layout, the underlying
    css-structure is simple in order to maximize compatibility with word processors
    such as 'MS Word' or 'LibreOffice'. The package also contains a few text formatting
    functions that help outputting text compatible with HTML/LaTeX.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
