appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qBTVjBy1cPVXM1iWVM3NlbOeUkhABUJkO0t2vsZu5A9LUibilX6ZgeWC1rpypF1dyiBetxkAsTdWl2zMnLoMB7WSeosR6OWJSaXdCIUwXXL67vw8XBERifuVERl7Xox9XCe9IO/m8JXdS5mtQQvt3gFijc8BfWi5KW0zmDefk8LjPSajlTn61fBSu0nNXOccKW2L9qv/uW9F8oDosSD2TMsAENLdaB06pspykFQD0rBniPzhpCSLsqFmNv3X2D2b/VECtJv62DvYCjR2nSGjwOzxTj2d6rQfMvv/3BLJPf2ddaeY+b29Z8JryBByyVhXZC4R1uCOBV/vNC4/hQiyOcLnQK33Udz4/OfIBXMEh9nFQx3JYCbje3fnbv1eqg//MppTiLQD/U3+JEWWzvNX/jQyUwRqXCdpUmxQowTqlQVXQJD9ofAD92zMeMPDhnn+42bVPm5AZ2SYvyz4OlM9MFvzGdW4hj2/s1yaUQQ1Ni0Y7HJpSBSmZoJ+vrlOWsZc/m4Myv2fahDXZ6JQzEBgz2MnAScckUluMxT5yq8lHs+bI7PuZ3F8mgg4uGzI8/PznMQNIC6xQn39DyMTRJ5bT/wri+JHc/ZDqO58DCEC8m9zTcInIZPfDzwjCcCM8OFWOKNz9oLieKJ0qMQ7OKL3J5905iMe4R+YBVxxcVYQUFE=}
